import { ajax } from 'jquery';
import { transactionData } from './bank-statement.json';
import { budget } from './budet.json';
import { method } from 'lodash';
import { trigger } from '@angular/animations';

export const forms = {
  loginForm: {
    email: {
      name: 'email',
      label: 'Email',
      type: 'text',
      validations: 'required|email',
      value: '',
    },
    password: {
      name: 'password',
      label: 'Password',
      type: 'text',
      validations: 'required',
      value: '',
    },
  },
  registrationForm: {
    firstName: {
      name: 'firstName',
      label: 'First Name',
      type: 'text',
      validations: 'required',
      value: '',
    },
    lastName: {
      name: 'lastName',
      label: 'Last Name',
      type: 'text',
      validations: 'required',
      value: '',
    },
    gender: {
      name: 'gender',
      label: 'Gender',
      type: 'select',
      validations: 'required',
      value: '',
      options: [
        {
          key: 'f',
          value: 'Female',
        },
        {
          key: 'm',
          value: 'Male',
        },
        {
          key: 't',
          value: 'Transgender',
        }
      ]
    },
    dob: {
      name: 'dob',
      label: 'Date Of Birth',
      type: 'date',
      validations: 'required',
      value: '',
    },
    mobileNo: {
      name: 'mobileNo',
      label: 'Mobile No',
      type: 'text',
      validations: 'required',
      value: '',
    },
    no: {
      name: 'no',
      label: 'OTP',
      type: 'text',
      validations: '',
      value: '',
    },
    email: {
      name: 'email',
      label: 'Email',
      type: 'text',
      validations: 'required|email',
      value: '',
    },
    password: {
      name: 'password',
      label: 'Password',
      type: 'text',
      validations: '',
      value: '',
    },
    confirmPassword: {
      name: 'confirmPassword',
      label: 'Confirm Password',
      type: 'text',
      validations: 'required_if:password',
      value: '',
    },
  },
  // login: [
  //     {
  //         "name": "email",
  //         "label": "Email",
  //         "type": "text",
  //         "order": 1,
  //         "col": 12,
  //         "validations": "required|email",
  //     },
  //     {
  //         "name": "password",
  //         "label": "Password",
  //         "type": "text",
  //         "order": 2,
  //         "col": 12,
  //         "validations": "required",
  //     }
  // ],
  registration: [],
  profileForm: {
    firstname: {
      fieldtype: 'text',
      col: '6',
      datatype: 'alphanumberic',
      name: 'firstName',
      label: 'Firstname',
      value: '',
      validations: 'required',
    },
    lastName: {
      fieldtype: 'text',
      col: '6',
      datatype: 'alphanumberic',
      name: 'lastName',
      label: 'Lastname',
      value: '',
      validations: 'required',
    },
    email: {
      fieldtype: 'text',
      col: '12',
      datatype: 'alphanumberic',
      name: 'email',
      label: 'Email',
      value: '',
      validations: 'required',
    },
  },
  changePasswordForm: {
    oldPassword: {
      fieldtype: 'text',
      col: '12',
      datatype: 'alphanumberic',
      name: 'oldPassword',
      label: 'Old Password',
      value: '',
      validations: 'required',
    },
    password: {
      fieldtype: 'text',
      col: '12',
      datatype: 'alphanumberic',
      name: 'password',
      label: 'New Password',
      value: '',
      validations: 'required',
    },
    confirmPassword: {
      fieldtype: 'text',
      col: '12',
      datatype: 'alphanumberic',
      name: 'confirmPassword',
      label: 'Confirm New Password',
      value: '',
      validations: 'required',
    },
  },
  transactionForm: {
    title: {
      fieldtype: 'text',
      col: '12',
      datatype: 'alphanumberic',
      name: 'title',
      label: 'Title',
      value: '',
      validations: 'required',
    },
    description: {
      fieldtype: 'text',
      datatype: 'alphanumberic',
      name: 'description',
      col: '12',
      label: 'Description',
      value: '',
      validations: 'required',
    },
    file: {
      fieldtype: 'file',
      datatype: 'alphanumberic',
      name: 'file',
      col: '12',
      label: 'File',
      multiple: false,
      value: null,
      validations: 'required',
    },
  },
  budgetForm: {
    type: {
      fieldtype: 'hidden',
      datatype: 'alpha',
      col: '12',
      name: 'type',
      label: 'Type',
      value: '',
      validations: 'required',
    },
    category: {
      fieldtype: 'select-ajax',
      datatype: 'alpha',
      col: '6',
      name: 'category',
      label: 'Category',
      value: '',
      validations: 'required',
      ajax: {
        uri: '/categories/list',
        data: {
          parentCode: '',
        },
        option: {
          key: 'code',
          value: 'title',
        },
      },
      options: [],
      triggerSelect: 'subcategory',
      
    },
    subcategory: {
      fieldtype: 'select-ajax',
      datatype: 'alpha',
      col: '6',
      name: 'subcategory',
      label: 'Sub Category',
      value: '',
      validations: 'required',
      ajax: {
        uri: '/categories/list',
        data: {
          parentCode: '',
        },
        option: {
          key: 'code',
          value: 'title',
        },
      },
      options: [],
      trigger: '',
    },
    title: {
      fieldtype: 'text',
      datatype: 'alpha',
      col: '12',
      name: 'title',
      label: 'Title',
      value: '',
      validations: 'required',
    },
    description: {
      fieldtype: 'text',
      datatype: 'alpha',
      col: '12',
      name: 'description',
      label: 'Description',
      value: '',
      validations: 'required',
    },
    amount: {
      fieldtype: 'text',
      datatype: 'alpha',
      col: '12',
      name: 'amount',
      label: 'Amount',
      value: 0,
      validations: 'required',
    },
  },
  plannerForm: {
    type: {
      fieldtype: 'hidden',
      datatype: 'alpha',
      col: '12',
      name: 'type',
      label: 'Type',
      value: '',
      validations: 'required',
    },
    title: {
      fieldtype: 'text',
      col: '12',
      datatype: 'alphanumberic',
      name: 'title',
      label: 'Title',
      value: '',
      validations: 'required',
    },
    description: {
      fieldtype: 'text',
      datatype: 'alphanumberic',
      name: 'description',
      col: '12',
      label: 'Description',
      value: '',
      validations: 'required',
    },
    principalAmount: {
      fieldtype: 'number',
      datatype: 'numeric',
      col: '12',
      name: 'principalAmount',
      label: 'Principal Paid Amount',
      value: 0,
      validations: 'required',
    },
    amount: {
      fieldtype: 'number',
      datatype: 'numeric',
      col: '12',
      name: 'amount',
      label: 'Amount',
      value: 0,
      validations: 'required',
    },
    rate: {
      fieldtype: 'number',
      datatype: 'numeric',
      col: '6',
      name: 'rate',
      label: 'Rate Of Interest (p.a.)',
      value: 0,
      validations: 'required',
    },
    tenure: {
      fieldtype: 'number',
      datatype: 'numeric',
      col: '6',
      name: 'tenure',
      label: 'Tenure (In-Years)',
      value: 0,
      validations: 'required',
    },
  },
  loanForm: {
    amount: {
      name: 'amount',
      label: 'Amount',
      value: 5000000,
      validations: 'required',
    },
    rate: {
      name: 'rate',
      label: 'Rate Of Interest (p.a.)',
      value: 9,
      validations: 'required',
    },
    tenure: {
      name: 'tenure',
      label: 'Tenure (In-Years)',
      value: 20,
      validations: 'required',
    },
    emi: {
      name: 'emi',
      label: 'EMI Amount',
      value: 0,
      validations: '',
    },
    growthRate: {
      name: 'growthRate',
      label: 'Annual Step-Up',
      value: 0,
      validations: '',
    },
    additionalAmount: {
      name: 'additionalAmount',
      label: 'Annual Part Payment',
      value: 0,
      validations: '',
    },

  },
};
