export const incomeTaxCategories = [
  {
    name: 'income',
    title: 'Income Details',
    fields: {
      salaryIncome: {
        fieldtype: 'text',
        col: '6',
        datatype: 'alphanumberic',
        name: 'oldPassword',
        label: 'Gross Income From Salary',
        value: '',
        validations: 'required',
      },
      interestIncome: {
        fieldtype: 'text',
        col: '6',
        datatype: 'alphanumberic',
        name: 'oldPassword',
        label: 'Income From Interest',
        value: '',
        validations: 'required',
      },
      rentalIncome: {
        fieldtype: 'text',
        col: '6',
        datatype: 'alphanumberic',
        name: 'oldPassword',
        label: 'Rental Income Received',
        value: '',
        validations: 'required',
      },
      otherIncome: {
        fieldtype: 'text',
        col: '6',
        datatype: 'alphanumberic',
        name: 'oldPassword',
        label: 'Income From Other Sources (Interest, Dividend, etc.)',
        value: '',
        validations: 'required',
      },
    },
  },
  {
    name: 'deduction',
    title: 'Deduction Details',
    fields: {
      under80c: {
        fieldtype: 'header',
        col: '12',
        datatype: 'alphanumberic',
        name: 'under80c',
        label: 'Under 80C',
        value: '',
        validations: 'required',
      },
      lifeInsurancePremium: {
        fieldtype: 'text',
        col: '6',
        datatype: 'alphanumberic',
        name: 'lifeInsurancePremium',
        label: 'Life Insurance Premium',
        value: '',
        validations: 'required',
      },
      healthInsurancePremium: {
        fieldtype: 'text',
        col: '6',
        datatype: 'alphanumberic',
        name: 'healthInsurancePremium',
        label: 'Health Insurance Premium',
        value: '',
        validations: 'required',
      },
      contributionToPPF: {
        fieldtype: 'text',
        col: '6',
        datatype: 'alphanumberic',
        name: 'contributionToPPF',
        label: 'Contribution to Public Provident Fund',
        value: '',
        validations: 'required',
      },
      contributionToPF: {
        fieldtype: 'text',
        col: '6',
        datatype: 'alphanumberic',
        name: 'contributionToPF',
        label: 'Contribution to Provident Fund',
        value: '',
        validations: 'required',
      },
      taxSavingFixedDeposit: {
        fieldtype: 'text',
        col: '6',
        datatype: 'alphanumberic',
        name: 'taxSavingFixedDeposit',
        label: 'Tax Saving Fixed Deposit',
        value: '',
        validations: 'required',
      },
      repaymentOfPrincipalOnHousingLoan: {
        fieldtype: 'text',
        col: '6',
        datatype: 'alphanumberic',
        name: 'repaymentOfPrincipalOnHousingLoan',
        label: 'Repayment of Principal on Housing Loan',
        value: '',
        validations: 'required',
      },
      ulipTaxSavingInvestmentPlans: {
        fieldtype: 'text',
        col: '6',
        datatype: 'alphanumberic',
        name: 'ulipTaxSavingInvestmentPlans',
        label: 'ULIP/ Tax Saving Investment Plans',
        value: '',
        validations: 'required',
      },
      equityLinkedSavingsSchemes: {
        fieldtype: 'text',
        col: '6',
        datatype: 'alphanumberic',
        name: 'equityLinkedSavingsSchemes',
        label: 'Equity Linked Savings Schemes (ELSS)',
        value: '',
        validations: 'required',
      },
      employeeContributionToNPS: {
        fieldtype: 'text',
        col: '6',
        datatype: 'alphanumberic',
        name: 'employeeContributionToNPS',
        label: 'Employee Contribution to NPS u/s 80CCD(1)',
        value: '',
        validations: 'required',
      },
      tuitionFees: {
        fieldtype: 'text',
        col: '6',
        datatype: 'alphanumberic',
        name: 'tuitionFees',
        label: 'Tuition Fees',
        value: '',
        validations: 'required',
      },
      otherTaxSavingInvestments: {
        fieldtype: 'text',
        col: '6',
        datatype: 'alphanumberic',
        name: 'otherTaxSavingInvestments',
        label: 'Other Tax Saving Investments u/s 80C',
        value: '',
        validations: 'required',
      },
      under80d: {
        fieldtype: 'header',
        col: '12',
        datatype: 'alphanumberic',
        name: 'under80D',
        label: 'Under 80D',
        value: '',
        validations: 'required',
      },
      preventiveCheckup: {
        fieldtype: 'text',
        col: '6',
        datatype: 'alphanumberic',
        name: 'preventiveCheckup',
        label: 'Preventive Checkup',
        value: '',
        validations: 'required',
      },
      forParentsBelow60Years: {
        fieldtype: 'text',
        col: '6',
        datatype: 'alphanumberic',
        name: 'forParentsBelow60Years',
        label: 'For Parents below 60 Years',
        value: '',
        validations: 'required',
      },
      forParentsAbove60Years: {
        fieldtype: 'text',
        col: '6',
        datatype: 'alphanumberic',
        name: 'forParentsAbove60Years',
        label: 'For Parents above 60 Years',
        value: '',
        validations: 'required',
      },
      hra: {
        fieldtype: 'text',
        col: '6',
        datatype: 'alphanumberic',
        name: 'hra',
        label: 'HRA u/s 10 (13A)',
        value: '',
        validations: 'required',
      },
       
      interestOnHousingLoanSection24: {
        fieldtype: 'text',
        col: '6',
        datatype: 'alphanumberic',
        name: 'interestOnHousingLoanSection24',
        label: 'Interest on Housing Loan Section 24',
        value: '',
        validations: 'required',
      },
      savingsAccountInterest: {
        fieldtype: 'text',
        col: '6',
        datatype: 'alphanumberic',
        name: 'savingsAccountInterest',
        label: 'Savings Account Interest (Section 80TTA)',
        value: '',
        validations: 'required',
      },
      professionalTax: {
        fieldtype: 'text',
        col: '6',
        datatype: 'alphanumberic',
        name: 'professionalTax',
        label: 'Professional Tax',
        value: '',
        validations: 'required',
      },
      donation: {
        fieldtype: 'text',
        col: '6',
        datatype: 'alphanumberic',
        name: 'donation',
        label: 'Donation u/s 80G',
        value: '',
        validations: 'required',
      },
      others: {
        fieldtype: 'text',
        col: '6',
        datatype: 'alphanumberic',
        name: 'others',
        label: 'Others',
        value: '',
        validations: 'required',
      },
    },
  },
];

export const incomeTaxSlabs = [
  {
    from: 0,
    to: 250000,
    oldrate: 0,
    rate: 0,
  },
  {
    from: 250001,
    to: 300000,
    oldrate: 0,
    rate: 0,
  },
  {
    from: 300001,
    to: 500000,
    oldrate: 0,
    rate: 5,
  },
  {
    from: 500001,
    to: 600000,
    oldrate: 5,
    rate: 5,
  },
  {
    from: 600001,
    to: 750000,
    oldrate: 10,
    rate2023: 10,
    rate: 10,
  },
  {
    from: 750001,
    to: 900000,
    oldrate: 10,
    rate2023: 10,
    rate: 10,
  },
  {
    from: 900001,
    to: 1000000,
    oldrate: 15,
    rate2023: 15,
    rate: 15,
  },
  {
    from: 1000001,
    to: 1200000,
    oldrate: 15,
    rate2023: 15,
    rate: 15,
  },
  {
    from: 1200001,
    to: 1250000,
    oldrate: 20,
    rate2023: 20,
    rate: 20,
  },
  {
    from: 1250001,
    to: 1500000,
    oldrate: 20,
    rate2023: 20,
    rate: 20,
  },
  {
    from: 1500001,
    to: 1000000000,
    oldrate: 30,
    rate2023: 30,
    rate: 30,
  }
]
